version: '3.6'

# The containers that compose the project
services:
    db:
        image: redis
        restart: always
        container_name: redis_billboard-client
        ports:
            - '6368:6368'
